### ISSUE TITLE
ReferenceError: rcpt_domains is not defined

### ISSUE THREAD

**Issue by analogic** [haraka/haraka-plugin-known-senders#14]
```
[known-senders] [ERROR] - update_sender: no sender domain
[core] [CRIT] - Plugin known-senders failed: ReferenceError: rcpt_domains is not defined
```

errNext() seems to be called in multiple cases without sender_od or rcpt_domains being defined
https://github.com/haraka/haraka-plugin-known-senders/blob/295b240bb38e92e316fcdd7cbc705911d6eed264/index.js#L44-L61

**Comment by msimerson** [comment]
Fixed in #15
