### ISSUE TITLE
Camel case calls to redis DB fail

### ISSUE THREAD

**Issue by DoobleD** [haraka/haraka-plugin-known-senders#32]
I often see a TypeError pop up right after a call to a hook in the plugin:

```
[DEBUG] [01A259E0-9381-4AA8-88EB-D01D6C90BDB9.1] [core] running queue_ok hook in known-senders plugin
[ERROR] [01A259E0-9381-4AA8-88EB-D01D6C90BDB9.1] [TypeError] 
```

After investigating, the issue occurs when calling redis's `hIncrBy` method in camel case [here](https://github.com/haraka/haraka-plugin-known-senders/blob/779c06a2ceee483f067367a4db250a322e44b78d/index.js#L69):

```
for (let i = 0; i < rcpt_domains.length; i++) {
  multi.hIncrBy(sender_od, rcpt_domains[i], 1);
}
```

Changing to a lowercase call (`hincrby`) resolves the issue. The same thing happens with calls to `hGet`, generating:

```
[ERROR] [DC779674-83A1-4C7B-B565-795E83F68707.1] [known-senders] is_dkim_authenticated: TypeError: multi.hGet is not a function
```

Versions:

```
root@mail:/usr/lib/node_modules/Haraka# npm list redis
Haraka@2.8.28 /usr/lib/node_modules/Haraka
├─┬ haraka-plugin-known-senders@1.0.9
│ └─┬ haraka-plugin-redis@2.0.5
│   └── redis@4.2.0 
├─┬ haraka-plugin-limit@1.0.7
│ ├─┬ haraka-plugin-redis@2.0.5
│ │ └── redis@4.2.0  deduped
│ └── redis@4.2.0 
├─┬ haraka-plugin-recipient-routes@1.0.3
│ ├─┬ haraka-plugin-redis@2.0.5
│ │ └── redis@4.2.0  deduped
│ └── redis@4.2.0 
├─┬ haraka-plugin-redis@1.0.13
│ └── redis@3.1.2  deduped
├─┬ haraka-results@2.2.2
│ └── redis@4.2.0 
└── redis@3.1.2 
```

It is unclear why the camel case calls fail, as the redis package apparently supports that.

**Comment by msimerson** [comment]
There's changes in the latest major redis client. I might not have updated the known senders plug-in yet.

**Comment by DoobleD** [comment]
Closing as this should be resolved on the master branch and in the coming Haraka 3 release. Similar to https://github.com/haraka/haraka-plugin-limit/issues/47.
